stages:
    - build
    - test

build:
    stage: build
    script:
        - echo "Building"
        - "dotnet build"
        - echo "Building complete"

test:
    stage: test
    script:
        - echo "Testing"
