stages:
    - build
    - test

build:
    stage: build
    
    script:
        - echo "Restore"
        - "dotnet restore"
        
        - echo "Build"
        - "dotnet build"

test:
    stage: test
    script:
        - echo "Testing"
