name: AuthenticationService

on:
  push:
    branches: [ develop ]
    paths:
      - AuthenticationServices/**
  pull_request:
    branches: [ develop ]
    paths:
      - AuthenticationServices/**

defaults:
  run:
    working-directory: .
    
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  build-docker:
    needs: [ build ]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build the docker AuthenticationService image
        run: docker build . --file AuthenticationServices/Kwetter.AuthenticationService/Dockerfile --tag kwetter-auth-service:$(date +%s)
